[versions]
kotlin = "2.2.21"
kotlinxSerialization = "1.9.0"

clikt = "5.0.3"
docker-kt = "v0.0.7"
kotlin-table = "v0.0.9"

[libraries]
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
docker-kt = { module = "io.github.julius-babies:docker.kt", version.ref = "docker-kt" }
tui-table = { module = "io.github.julius-babies:table-tui", version.ref = "kotlin-table" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
